apiVersion: v1
kind: Service
metadata:
  name: civ4bot
  namespace: civ4bot
  labels:
    app.kubernetes.io/name: civ4bot
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: civ4bot
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
